disabled_rules:
  - comment_spacing
  - trailing_whitespace

#  - force_cast
#  - force_try
#
#  # SwiftLint is having issues with my Carthage frameworks, have to disable this even though
#  # the rule isn't being violated
#
#  - identifier_name

#line_length: 150
#
#type_body_length:
#  warning: 1000
#  error: 1500
#
#file_length:
#  warning: 1000
#  error: 1500
#
#identifier_name:
#  excluded:
#    - id

#nesting:
#  type_level:
#    warning: 2

excluded:
  - Pods
  - IntegrationSpecs
